/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UrlRouteImport } from './routes/url'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as ProfileSearchRouteImport } from './routes/profile-search'
import { Route as FraudRouteImport } from './routes/fraud'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImageSearchIndexRouteImport } from './routes/image-search/index'
import { Route as ImageSearchResultRouteImport } from './routes/image-search/result'
import { Route as AnalyzeIdRouteImport } from './routes/analyze/$id'

const UrlRoute = UrlRouteImport.update({
  id: '/url',
  path: '/url',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSearchRoute = ProfileSearchRouteImport.update({
  id: '/profile-search',
  path: '/profile-search',
  getParentRoute: () => rootRouteImport,
} as any)
const FraudRoute = FraudRouteImport.update({
  id: '/fraud',
  path: '/fraud',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageSearchIndexRoute = ImageSearchIndexRouteImport.update({
  id: '/image-search/',
  path: '/image-search/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageSearchResultRoute = ImageSearchResultRouteImport.update({
  id: '/image-search/result',
  path: '/image-search/result',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeIdRoute = AnalyzeIdRouteImport.update({
  id: '/analyze/$id',
  path: '/analyze/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/fraud': typeof FraudRoute
  '/profile-search': typeof ProfileSearchRoute
  '/training': typeof TrainingRoute
  '/url': typeof UrlRoute
  '/analyze/$id': typeof AnalyzeIdRoute
  '/image-search/result': typeof ImageSearchResultRoute
  '/image-search/': typeof ImageSearchIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/fraud': typeof FraudRoute
  '/profile-search': typeof ProfileSearchRoute
  '/training': typeof TrainingRoute
  '/url': typeof UrlRoute
  '/analyze/$id': typeof AnalyzeIdRoute
  '/image-search/result': typeof ImageSearchResultRoute
  '/image-search': typeof ImageSearchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/fraud': typeof FraudRoute
  '/profile-search': typeof ProfileSearchRoute
  '/training': typeof TrainingRoute
  '/url': typeof UrlRoute
  '/analyze/$id': typeof AnalyzeIdRoute
  '/image-search/result': typeof ImageSearchResultRoute
  '/image-search/': typeof ImageSearchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/fraud'
    | '/profile-search'
    | '/training'
    | '/url'
    | '/analyze/$id'
    | '/image-search/result'
    | '/image-search/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/fraud'
    | '/profile-search'
    | '/training'
    | '/url'
    | '/analyze/$id'
    | '/image-search/result'
    | '/image-search'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/fraud'
    | '/profile-search'
    | '/training'
    | '/url'
    | '/analyze/$id'
    | '/image-search/result'
    | '/image-search/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  FraudRoute: typeof FraudRoute
  ProfileSearchRoute: typeof ProfileSearchRoute
  TrainingRoute: typeof TrainingRoute
  UrlRoute: typeof UrlRoute
  AnalyzeIdRoute: typeof AnalyzeIdRoute
  ImageSearchResultRoute: typeof ImageSearchResultRoute
  ImageSearchIndexRoute: typeof ImageSearchIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/url': {
      id: '/url'
      path: '/url'
      fullPath: '/url'
      preLoaderRoute: typeof UrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-search': {
      id: '/profile-search'
      path: '/profile-search'
      fullPath: '/profile-search'
      preLoaderRoute: typeof ProfileSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fraud': {
      id: '/fraud'
      path: '/fraud'
      fullPath: '/fraud'
      preLoaderRoute: typeof FraudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-search/': {
      id: '/image-search/'
      path: '/image-search'
      fullPath: '/image-search/'
      preLoaderRoute: typeof ImageSearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-search/result': {
      id: '/image-search/result'
      path: '/image-search/result'
      fullPath: '/image-search/result'
      preLoaderRoute: typeof ImageSearchResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze/$id': {
      id: '/analyze/$id'
      path: '/analyze/$id'
      fullPath: '/analyze/$id'
      preLoaderRoute: typeof AnalyzeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  FraudRoute: FraudRoute,
  ProfileSearchRoute: ProfileSearchRoute,
  TrainingRoute: TrainingRoute,
  UrlRoute: UrlRoute,
  AnalyzeIdRoute: AnalyzeIdRoute,
  ImageSearchResultRoute: ImageSearchResultRoute,
  ImageSearchIndexRoute: ImageSearchIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
