/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UrlRouteImport } from './routes/url'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as FraudRouteImport } from './routes/fraud'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyIndexRouteImport } from './routes/verify/index'
import { Route as ProfileSearchIndexRouteImport } from './routes/profile-search/index'
import { Route as ImageSearchIndexRouteImport } from './routes/image-search/index'
import { Route as AnalyzeIndexRouteImport } from './routes/analyze/index'
import { Route as VerifyResultRouteImport } from './routes/verify/result'
import { Route as ProfileSearchResultRouteImport } from './routes/profile-search/result'
import { Route as ImageSearchResultRouteImport } from './routes/image-search/result'
import { Route as AnalyzeIdRouteImport } from './routes/analyze/$id'

const UrlRoute = UrlRouteImport.update({
  id: '/url',
  path: '/url',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const FraudRoute = FraudRouteImport.update({
  id: '/fraud',
  path: '/fraud',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyIndexRoute = VerifyIndexRouteImport.update({
  id: '/verify/',
  path: '/verify/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSearchIndexRoute = ProfileSearchIndexRouteImport.update({
  id: '/profile-search/',
  path: '/profile-search/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageSearchIndexRoute = ImageSearchIndexRouteImport.update({
  id: '/image-search/',
  path: '/image-search/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeIndexRoute = AnalyzeIndexRouteImport.update({
  id: '/analyze/',
  path: '/analyze/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyResultRoute = VerifyResultRouteImport.update({
  id: '/verify/result',
  path: '/verify/result',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSearchResultRoute = ProfileSearchResultRouteImport.update({
  id: '/profile-search/result',
  path: '/profile-search/result',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageSearchResultRoute = ImageSearchResultRouteImport.update({
  id: '/image-search/result',
  path: '/image-search/result',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeIdRoute = AnalyzeIdRouteImport.update({
  id: '/analyze/$id',
  path: '/analyze/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/fraud': typeof FraudRoute
  '/training': typeof TrainingRoute
  '/url': typeof UrlRoute
  '/analyze/$id': typeof AnalyzeIdRoute
  '/image-search/result': typeof ImageSearchResultRoute
  '/profile-search/result': typeof ProfileSearchResultRoute
  '/verify/result': typeof VerifyResultRoute
  '/analyze/': typeof AnalyzeIndexRoute
  '/image-search/': typeof ImageSearchIndexRoute
  '/profile-search/': typeof ProfileSearchIndexRoute
  '/verify/': typeof VerifyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/fraud': typeof FraudRoute
  '/training': typeof TrainingRoute
  '/url': typeof UrlRoute
  '/analyze/$id': typeof AnalyzeIdRoute
  '/image-search/result': typeof ImageSearchResultRoute
  '/profile-search/result': typeof ProfileSearchResultRoute
  '/verify/result': typeof VerifyResultRoute
  '/analyze': typeof AnalyzeIndexRoute
  '/image-search': typeof ImageSearchIndexRoute
  '/profile-search': typeof ProfileSearchIndexRoute
  '/verify': typeof VerifyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/fraud': typeof FraudRoute
  '/training': typeof TrainingRoute
  '/url': typeof UrlRoute
  '/analyze/$id': typeof AnalyzeIdRoute
  '/image-search/result': typeof ImageSearchResultRoute
  '/profile-search/result': typeof ProfileSearchResultRoute
  '/verify/result': typeof VerifyResultRoute
  '/analyze/': typeof AnalyzeIndexRoute
  '/image-search/': typeof ImageSearchIndexRoute
  '/profile-search/': typeof ProfileSearchIndexRoute
  '/verify/': typeof VerifyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/fraud'
    | '/training'
    | '/url'
    | '/analyze/$id'
    | '/image-search/result'
    | '/profile-search/result'
    | '/verify/result'
    | '/analyze/'
    | '/image-search/'
    | '/profile-search/'
    | '/verify/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/fraud'
    | '/training'
    | '/url'
    | '/analyze/$id'
    | '/image-search/result'
    | '/profile-search/result'
    | '/verify/result'
    | '/analyze'
    | '/image-search'
    | '/profile-search'
    | '/verify'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/fraud'
    | '/training'
    | '/url'
    | '/analyze/$id'
    | '/image-search/result'
    | '/profile-search/result'
    | '/verify/result'
    | '/analyze/'
    | '/image-search/'
    | '/profile-search/'
    | '/verify/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  FraudRoute: typeof FraudRoute
  TrainingRoute: typeof TrainingRoute
  UrlRoute: typeof UrlRoute
  AnalyzeIdRoute: typeof AnalyzeIdRoute
  ImageSearchResultRoute: typeof ImageSearchResultRoute
  ProfileSearchResultRoute: typeof ProfileSearchResultRoute
  VerifyResultRoute: typeof VerifyResultRoute
  AnalyzeIndexRoute: typeof AnalyzeIndexRoute
  ImageSearchIndexRoute: typeof ImageSearchIndexRoute
  ProfileSearchIndexRoute: typeof ProfileSearchIndexRoute
  VerifyIndexRoute: typeof VerifyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/url': {
      id: '/url'
      path: '/url'
      fullPath: '/url'
      preLoaderRoute: typeof UrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fraud': {
      id: '/fraud'
      path: '/fraud'
      fullPath: '/fraud'
      preLoaderRoute: typeof FraudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/': {
      id: '/verify/'
      path: '/verify'
      fullPath: '/verify/'
      preLoaderRoute: typeof VerifyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-search/': {
      id: '/profile-search/'
      path: '/profile-search'
      fullPath: '/profile-search/'
      preLoaderRoute: typeof ProfileSearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-search/': {
      id: '/image-search/'
      path: '/image-search'
      fullPath: '/image-search/'
      preLoaderRoute: typeof ImageSearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze/': {
      id: '/analyze/'
      path: '/analyze'
      fullPath: '/analyze/'
      preLoaderRoute: typeof AnalyzeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/result': {
      id: '/verify/result'
      path: '/verify/result'
      fullPath: '/verify/result'
      preLoaderRoute: typeof VerifyResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-search/result': {
      id: '/profile-search/result'
      path: '/profile-search/result'
      fullPath: '/profile-search/result'
      preLoaderRoute: typeof ProfileSearchResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-search/result': {
      id: '/image-search/result'
      path: '/image-search/result'
      fullPath: '/image-search/result'
      preLoaderRoute: typeof ImageSearchResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze/$id': {
      id: '/analyze/$id'
      path: '/analyze/$id'
      fullPath: '/analyze/$id'
      preLoaderRoute: typeof AnalyzeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  FraudRoute: FraudRoute,
  TrainingRoute: TrainingRoute,
  UrlRoute: UrlRoute,
  AnalyzeIdRoute: AnalyzeIdRoute,
  ImageSearchResultRoute: ImageSearchResultRoute,
  ProfileSearchResultRoute: ProfileSearchResultRoute,
  VerifyResultRoute: VerifyResultRoute,
  AnalyzeIndexRoute: AnalyzeIndexRoute,
  ImageSearchIndexRoute: ImageSearchIndexRoute,
  ProfileSearchIndexRoute: ProfileSearchIndexRoute,
  VerifyIndexRoute: VerifyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
